name: gradle build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: config jdk 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: permit build
      run: chmod +x gradlew
    - name: execute build
      run: ./gradlew build
